Algoritmo "dia da semana v2"

Var

x : inteiro
dia : caractere

Inicio

escreval ("Fui aprovado?")
escreval
escreva ("Digite o dia da semana em número: ")
leia (x)
escreval
escreval

escolha (x)

caso 1
     dia <- "domingo"
caso 2
     dia <- "segunda-feira"
caso 3
     dia <- "terça-feira"
caso 4
     dia <- "quarta-feira"
caso 5
     dia <- "quinta-feira"
caso 6
     dia <- "sexta-feira"
caso 7
     dia <- "sábado"
outrocaso
     dia <- "Dia invalido"
fimescolha

escreval (dia)

Fimalgoritmo