algoritmo "Consumo medio de gasosa"

var

distancia, gasto, m : real

inicio
escreva ("Qual a distância percurrida em KM: ")
leia (distancia)
Escreva ("Qual o gasto de combustível: ")
leia (gasto)
m <- distancia / gasto

escreval
escreval ("_____________________________")
escreval
escreval ("Distância percurrida: ", distancia:10:2, " Km")
escreval ("Combustível  gasto: ", gasto:12:2, (" L"))
escreval ("Consumo medio: ", m:17:2, " L por Km")
fimalgoritmo


