Algoritmo "Conversão de distância"

Var

m, km, hm, dam, dm, cm, mm : real

Inicio

escreva ("Digite uma distância em metros: ")
leia (m)

km <- m / 1000
hm <- m / 100
dam <- m / 10
dm <- m * 10
cm <- m * 100
mm <- m * 1000


escreval ("A distâncida de ", m, " corresponde a:" )
escreval
escreval (km, " km")
escreval (hm, " hm")
escreval (dam, " dam")
escreval (dm, " dm")
escreval (cm, " cm")
escreval (mm, " mm")

Fimalgoritmo