Algoritmo "cálculo geometrico de um círculo"


Var

r, a, d, c : real

Inicio
escreval ("CÍRCULO")
escreval
escreva ("Digite o raio do circulo: ")
leia (r)
a <- pi * r^2
d <- 2 * r
c <- (2 * pi) * r

escreval ("_____________________________________")
escreval
escreval ("O diametro do circulo é: ", d:14:3)
escreval ("A área do círculo é: ", a:18:3)
escreval ("A circunferencia do circulo é: ", c:8:3)
Fimalgoritmo